{{- range $key, $value := .Values.repositories }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}